//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TravelBudget
    {
        public int id { get; set; }
        public Nullable<int> TripSheetNo { get; set; }
        public string MachineNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Purpose { get; set; }
        public string Cluster { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RequestForId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public string Zone { get; set; }
        public Nullable<int> EstDistanceKms { get; set; }
        public Nullable<System.TimeSpan> EstTravelTime { get; set; }
        public Nullable<System.TimeSpan> FoodFuelOthers { get; set; }
        public Nullable<System.TimeSpan> EstJobTime { get; set; }
        public Nullable<System.TimeSpan> SchdET { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> TotalEstDistKms { get; set; }
        public Nullable<System.TimeSpan> TotalEstTravelTime { get; set; }
        public Nullable<System.TimeSpan> TotalFoodFuel { get; set; }
        public Nullable<System.TimeSpan> TotalEstJobTime { get; set; }
        public Nullable<System.TimeSpan> TotalSchdET { get; set; }
        public Nullable<int> MileageCNG { get; set; }
        public Nullable<int> MileagePetrol { get; set; }
        public Nullable<int> MileageDiesel { get; set; }
        public Nullable<decimal> FuelPriceCNG { get; set; }
        public Nullable<decimal> FuelPricePetrol { get; set; }
        public Nullable<decimal> FuelPriceDiesel { get; set; }
        public Nullable<decimal> FuelPriceReqd { get; set; }
        public Nullable<decimal> FuelReqd { get; set; }
        public string SparesReqd { get; set; }
        public string Vehicle { get; set; }
        public string StartPlace { get; set; }
        public string StartCluster { get; set; }
        public string EndPlace { get; set; }
        public string EndCluster { get; set; }
        public Nullable<System.TimeSpan> InitialTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
