//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_InvoiceDocuments
    {
        public int Id { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string InvoiceName { get; set; }
        public string BlobLink { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<bool> IsMachineDeleted { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelName { get; set; }
        public string CustomerName { get; set; }
    }
}
