//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Contactdetails
    {
        public int Id { get; set; }
        public string Salute { get; set; }
        public string ContactName { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ContactDetailsID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<bool> IsMachineDeleted { get; set; }
    }
}
