//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Quotationtemplate
    {
        public int RefID { get; set; }
        public string YourEnquiry { get; set; }
        public string KindAttention { get; set; }
        public string BillingAddress { get; set; }
        public string TelephoneNo { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
