//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MachineRegistration
    {
        public int Id { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Features { get; set; }
        public Nullable<int> FeaturesId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string InvoiceFileBlob { get; set; }
        public Nullable<int> InvoicePerticularId { get; set; }
        public string InvoicePerticular { get; set; }
        public Nullable<System.DateTime> WarrantyFrom { get; set; }
        public Nullable<System.DateTime> WarrantyTill { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsMachineDeleted { get; set; }
        public string ContactDataID { get; set; }
        public string FeatureDetailsID { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}
