//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_QUOTATION40202inDollor
    {
        public int ID { get; set; }
        public Nullable<int> RefID { get; set; }
        public string YourEnquiry { get; set; }
        public string BillingAddress { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public string BasicSystemQty { get; set; }
        public string BasicSystemPrice { get; set; }
        public string OptionalQtyA { get; set; }
        public string OptionalPriceA { get; set; }
        public string OptionalQtyB { get; set; }
        public string OptionalPriceB { get; set; }
        public string OptionalQtyC { get; set; }
        public string OptionalPriceC { get; set; }
        public string OptionalQtyD { get; set; }
        public string OptionalPriceD { get; set; }
        public string OptionalPriceE { get; set; }
        public string OptionalQtyF { get; set; }
        public string OptionalPriceF { get; set; }
        public string OptionalQtyG { get; set; }
        public string OptionalPriceG { get; set; }
        public string OptionalQtyH { get; set; }
        public string OptionalPriceH { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string OptionalQtyE { get; set; }
        public string KindAttention { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    }
}
