//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MachineCustomerSansSDetails
    {
        public int Id { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string SandS { get; set; }
        public Nullable<int> SandSId { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UniqueID { get; set; }
        public Nullable<bool> IsMachineDeleted { get; set; }
    }
}
