//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CallTicketScreen
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> TicketNo { get; set; }
        public string RequestFor { get; set; }
        public Nullable<int> RequestForId { get; set; }
        public string Priority { get; set; }
        public string Fault { get; set; }
        public string Resolution { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
