//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LocationDetails
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public string RoadCondition { get; set; }
        public string InsideCityOutsideCity { get; set; }
        public string NearbyLodge { get; set; }
        public string NearbyPetrolBunk { get; set; }
        public string HotelType { get; set; }
        public string NearbyMedicalShop { get; set; }
        public string NearbyHospital { get; set; }
        public string NearbyMechanicShops { get; set; }
        public string WhatToCarry { get; set; }
        public string TextArea { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string BestHotels { get; set; }
        public Nullable<int> ClusterId { get; set; }
    }
}
