//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPL.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MachineFeatureDetails
    {
        public int ID { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public string FeatureName { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> MachineNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string InvoiceParticulars { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string ModelName { get; set; }
        public Nullable<System.DateTime> WarrantyFrom { get; set; }
        public Nullable<System.DateTime> WarrantyTill { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string FeatureDataID { get; set; }
        public Nullable<bool> IsMachineDeleted { get; set; }
    }
}
